language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - tools
    - android-26
    - extra-android-m2repository
    - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - echo y | android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository"
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - pip install --user codecov

script:
   - ./gradlew build jacocoTestReport
   - ./gradlew connectedCheck

after_success:
   - codecov
   - bash <(curl -s https://codecov.io/bash)
